CREATE TABLE P_KEY
(
   P_OBJ_ID      NUMBER (38) CONSTRAINT P_KEY_P_OBJ_ID_NN NOT NULL,
   P_PTYPE_ID    NUMBER (38) CONSTRAINT P_KEY_P_PTYPE_NN NOT NULL,
   P_TECH_ID     NUMBER (38) CONSTRAINT P_KEY_P_TECH_ID_NN NOT NULL,
   COLUMN_NAME   VARCHAR2 (30 CHAR) CONSTRAINT P_KEY_COLUMN_NAME_NN NOT NULL,
   ENABLED       NUMBER (1) DEFAULT 0 CONSTRAINT P_KEY_ENABLED_NN NOT NULL
)
TABLESPACE &DATA_TBS.;

COMMENT ON TABLE P_KEY IS 'Column definition';

COMMENT ON COLUMN P_KEY.P_OBJ_ID IS 'Table the partition key belongs to';

COMMENT ON COLUMN P_KEY.P_PTYPE_ID IS 'Partition type.';

COMMENT ON COLUMN P_KEY.P_TECH_ID IS
   'Partition technique used for this partition key';

COMMENT ON COLUMN P_KEY.COLUMN_NAME IS
   'Column name which is the partition key';

COMMENT ON COLUMN P_KEY.ENABLED IS
   'Is this column handled by Partitionhandler';

CREATE INDEX P_KEY_ENABLED_IX
   ON P_KEY (ENABLED)
   TABLESPACE &INDEX_TBS.;

CREATE UNIQUE INDEX P_KEY_P_OBJ_ID_COLUMN_NAME_UX
   ON P_KEY (P_OBJ_ID, COLUMN_NAME)
   TABLESPACE &INDEX_TBS.;


CREATE UNIQUE INDEX P_KEY_P_OBJ_ID_P_PTYPE_ID_UX
   ON P_KEY (P_OBJ_ID, P_PTYPE_ID)
   TABLESPACE &INDEX_TBS.;


ALTER TABLE P_KEY ADD
  CONSTRAINT P_KEY_ENABLED_CK
  CHECK (enabled IN (0, 1))
  ENABLE VALIDATE;
ALTER TABLE P_KEY ADD  CONSTRAINT P_KEY_PK
  PRIMARY KEY
  (P_OBJ_ID, P_PTYPE_ID)
  USING INDEX P_KEY_P_OBJ_ID_P_PTYPE_ID_UX
  ENABLE VALIDATE;
ALTER TABLE P_KEY ADD  CONSTRAINT P_KEY_P_OBJ_ID_COLUMN_NAME_UK
  UNIQUE (P_OBJ_ID, COLUMN_NAME)
  USING INDEX P_KEY_P_OBJ_ID_COLUMN_NAME_UX
  ENABLE VALIDATE;


ALTER TABLE P_KEY ADD  CONSTRAINT P_KEY_P_OBJ_FK
  FOREIGN KEY (P_OBJ_ID)
  REFERENCES P_OBJ (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;
ALTER TABLE P_KEY ADD  CONSTRAINT P_KEY_P_PTYPE_FK
  FOREIGN KEY (P_PTYPE_ID)
  REFERENCES P_PTYPE (ID)
  ENABLE VALIDATE;
ALTER TABLE P_KEY ADD  CONSTRAINT P_KEY_P_TECH_FK
  FOREIGN KEY (P_TECH_ID)
  REFERENCES P_TECH (ID)
  ENABLE VALIDATE;