CREATE TABLE P_OTYPE
(
   ID            NUMBER (38) CONSTRAINT P_OTYPE_ID_NN NOT NULL,
   NAME          VARCHAR2 (30 CHAR) CONSTRAINT P_OTYPE_NAME_NN NOT NULL,
   DESCRIPTION   VARCHAR2 (255 CHAR)
                    CONSTRAINT P_OTYPE_DESCRIPTION_NN NOT NULL
)
TABLESPACE &DATA_TBS.;

INSERT INTO &OWNER_USER..p_otype (id, name, description)
     VALUES (1, 'TABLE', 'Partition definition is for a table');

INSERT INTO &OWNER_USER..p_otype (id, name, description)
     VALUES (2, 'INDEX', 'Partition definition is for an index');

ALTER TABLE P_OTYPE
READ ONLY;

CREATE UNIQUE INDEX P_OTYPE_ID_UX
   ON P_OTYPE (ID)
   TABLESPACE &INDEX_TBS.;

CREATE UNIQUE INDEX P_OTYPE_NAME_UX
   ON P_OTYPE (NAME)
   TABLESPACE &INDEX_TBS.;

ALTER TABLE P_OTYPE ADD
  CONSTRAINT P_OTYPE_PK
  PRIMARY KEY
  (ID);

ALTER TABLE P_OTYPE ADD CONSTRAINT P_OTYPE_NAME_PK
  UNIQUE (NAME);